<?php

/**
 * This is the model base class for the table "client".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Client".
 *
 * Columns in table "client" available as properties of the model,
 * followed by relations of table "client" available as properties of the model.
 *
 * @property integer $client_id
 * @property integer $user_id
 * @property string $unsaved_doc
 * @property integer $manager_id
 *
 * @property User $user
 * @property Manager $manager
 */
abstract class BaseClient extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'client';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Client|Clients', $n);
	}

	public static function representingColumn() {
		return 'unsaved_doc';
	}

	public function rules() {
		return array(
			array('user_id, manager_id', 'required'),
			array('user_id, manager_id', 'numerical', 'integerOnly'=>true),
			array('unsaved_doc', 'length', 'max'=>45),
			array('unsaved_doc', 'default', 'setOnEmpty' => true, 'value' => null),
			array('client_id, user_id, unsaved_doc, manager_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'manager' => array(self::BELONGS_TO, 'Manager', 'manager_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'client_id' => Yii::t('app', 'Client'),
			'user_id' => null,
			'unsaved_doc' => Yii::t('app', 'Unsaved Doc'),
			'manager_id' => null,
			'user' => null,
			'manager' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('client_id', $this->client_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('unsaved_doc', $this->unsaved_doc, true);
		$criteria->compare('manager_id', $this->manager_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}