<?php

/**
 * This is the model base class for the table "offer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Offer".
 *
 * Columns in table "offer" available as properties of the model,
 * followed by relations of table "offer" available as properties of the model.
 *
 * @property integer $offer_id
 * @property integer $official_id
 * @property integer $firm_type
 * @property string $firm_name
 * @property string $ceo
 * @property string $inn
 * @property string $kpp
 * @property string $payacc
 * @property string $bank
 * @property string $bik
 * @property string $coracc
 * @property string $okpo
 * @property string $regnum
 * @property integer $offer_type
 * @property integer $offer_type_id
 *
 * @property Official $official
 */
abstract class BaseOffer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'offer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Offer|Offers', $n);
	}

	public static function representingColumn() {
		return 'ceo';
	}

	public function rules() {
		return array(
			array('official_id, ceo, offer_type, offer_type_id', 'required'),
			array('official_id, firm_type, offer_type, offer_type_id', 'numerical', 'integerOnly'=>true),
			array('firm_name, ceo', 'length', 'max'=>100),
			array('inn', 'length', 'max'=>15),
			array('kpp, bik, okpo', 'length', 'max'=>12),
			array('payacc', 'length', 'max'=>30),
			array('bank', 'length', 'max'=>250),
			array('coracc', 'length', 'max'=>25),
			array('regnum', 'length', 'max'=>45),
			array('firm_type, firm_name, inn, kpp, payacc, bank, bik, coracc, okpo, regnum', 'default', 'setOnEmpty' => true, 'value' => null),
			array('offer_id, official_id, firm_type, firm_name, ceo, inn, kpp, payacc, bank, bik, coracc, okpo, regnum, offer_type, offer_type_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'official' => array(self::BELONGS_TO, 'Official', 'official_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'offer_id' => Yii::t('app', 'Offer'),
			'official_id' => null,
			'firm_type' => Yii::t('app', 'Firm Type'),
			'firm_name' => Yii::t('app', 'Firm Name'),
			'ceo' => Yii::t('app', 'Ceo'),
			'inn' => Yii::t('app', 'Inn'),
			'kpp' => Yii::t('app', 'Kpp'),
			'payacc' => Yii::t('app', 'Payacc'),
			'bank' => Yii::t('app', 'Bank'),
			'bik' => Yii::t('app', 'Bik'),
			'coracc' => Yii::t('app', 'Coracc'),
			'okpo' => Yii::t('app', 'Okpo'),
			'regnum' => Yii::t('app', 'Regnum'),
			'offer_type' => Yii::t('app', 'Offer Type'),
			'offer_type_id' => Yii::t('app', 'Offer Type'),
			'official' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('offer_id', $this->offer_id);
		$criteria->compare('official_id', $this->official_id);
		$criteria->compare('firm_type', $this->firm_type);
		$criteria->compare('firm_name', $this->firm_name, true);
		$criteria->compare('ceo', $this->ceo, true);
		$criteria->compare('inn', $this->inn, true);
		$criteria->compare('kpp', $this->kpp, true);
		$criteria->compare('payacc', $this->payacc, true);
		$criteria->compare('bank', $this->bank, true);
		$criteria->compare('bik', $this->bik, true);
		$criteria->compare('coracc', $this->coracc, true);
		$criteria->compare('okpo', $this->okpo, true);
		$criteria->compare('regnum', $this->regnum, true);
		$criteria->compare('offer_type', $this->offer_type);
		$criteria->compare('offer_type_id', $this->offer_type_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}