<?php

/**
 * This is the model base class for the table "user_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserInfo".
 *
 * Columns in table "user_info" available as properties of the model,
 * followed by relations of table "user_info" available as properties of the model.
 *
 * @property integer $user_info_id
 * @property integer $user_id
 * @property string $name
 * @property string $second_name
 * @property string $surname
 * @property string $phone
 * @property string $email
 * @property integer $manager_id
 *
 * @property User $user
 * @property Manager $manager
 */
abstract class BaseUserInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserInfo|UserInfos', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('user_id, name, second_name, surname, phone, email, manager_id', 'required'),
			array('user_id, manager_id', 'numerical', 'integerOnly'=>true),
			array('name, second_name, surname', 'length', 'max'=>45),
			array('phone', 'length', 'max'=>25),
			array('email', 'length', 'max'=>100),
			array('user_info_id, user_id, name, second_name, surname, phone, email, manager_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'manager' => array(self::BELONGS_TO, 'Manager', 'manager_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_info_id' => Yii::t('app', 'User Info'),
			'user_id' => null,
			'name' => Yii::t('app', 'Name'),
			'second_name' => Yii::t('app', 'Second Name'),
			'surname' => Yii::t('app', 'Surname'),
			'phone' => Yii::t('app', 'Phone'),
			'email' => Yii::t('app', 'Email'),
			'manager_id' => null,
			'user' => null,
			'manager' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_info_id', $this->user_info_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('second_name', $this->second_name, true);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('manager_id', $this->manager_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}