<?php

/**
 * This is the model base class for the table "device_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeviceStatus".
 *
 * Columns in table "device_status" available as properties of the model,
 * followed by relations of table "device_status" available as properties of the model.
 *
 * @property integer $device_status_id
 * @property string $device_status_desrc
 *
 * @property Device[] $devices
 */
abstract class BaseDeviceStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'device_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DeviceStatus|DeviceStatuses', $n);
	}

	public static function representingColumn() {
		return 'device_status_desrc';
	}

	public function rules() {
		return array(
			array('device_status_desrc', 'required'),
			array('device_status_desrc', 'length', 'max'=>45),
			array('device_status_id, device_status_desrc', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'devices' => array(self::HAS_MANY, 'Device', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'device_status_id' => Yii::t('app', 'Device Status'),
			'device_status_desrc' => Yii::t('app', 'Device Status Desrc'),
			'devices' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('device_status_id', $this->device_status_id);
		$criteria->compare('device_status_desrc', $this->device_status_desrc, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}