<?php

/**
 * This is the model base class for the table "account".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Account".
 *
 * Columns in table "account" available as properties of the model,
 * followed by relations of table "account" available as properties of the model.
 *
 * @property integer $account_id
 * @property integer $official_id
 * @property string $kpp
 * @property string $payacc
 * @property string $bank
 * @property string $bik
 * @property string $coracc
 * @property string $okpo
 *
 * @property Official $official
 */
abstract class BaseAccount extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Account|Accounts', $n);
	}

	public static function representingColumn() {
		return 'payacc';
	}

	public function rules() {
		return array(
			array('kpp, payacc, bank, bik, coracc, okpo', 'required'),
			array('official_id', 'numerical', 'integerOnly'=>true),
			array('kpp, bik, okpo', 'length', 'max'=>12),
			array('payacc', 'length', 'max'=>30),
			array('bank', 'length', 'max'=>250),
			array('coracc', 'length', 'max'=>25),
			array('official_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('account_id, official_id, kpp, payacc, bank, bik, coracc, okpo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'official' => array(self::BELONGS_TO, 'Official', 'official_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'account_id' => Yii::t('app', 'Account'),
			'official_id' => null,
			'kpp' => Yii::t('app', 'Kpp'),
			'payacc' => Yii::t('app', 'Payacc'),
			'bank' => Yii::t('app', 'Bank'),
			'bik' => Yii::t('app', 'Bik'),
			'coracc' => Yii::t('app', 'Coracc'),
			'okpo' => Yii::t('app', 'Okpo'),
			'official' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('account_id', $this->account_id);
		$criteria->compare('official_id', $this->official_id);
		$criteria->compare('kpp', $this->kpp, true);
		$criteria->compare('payacc', $this->payacc, true);
		$criteria->compare('bank', $this->bank, true);
		$criteria->compare('bik', $this->bik, true);
		$criteria->compare('coracc', $this->coracc, true);
		$criteria->compare('okpo', $this->okpo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}