<?php

/**
 * This is the model base class for the table "manager_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ManagerInfo".
 *
 * Columns in table "manager_info" available as properties of the model,
 * followed by relations of table "manager_info" available as properties of the model.
 *
 * @property integer $manager_info_id
 * @property string $name
 * @property string $second_name
 * @property string $surname
 * @property string $phone
 * @property string $email
 * @property string $unposted_docs
 *
 * @property Manager $managerInfo
 */
abstract class BaseManagerInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'manager_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ManagerInfo|ManagerInfos', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, second_name, surname, phone, email', 'required'),
			array('name, second_name, surname', 'length', 'max'=>45),
			array('phone', 'length', 'max'=>25),
			array('email', 'length', 'max'=>100),
			array('unposted_docs', 'length', 'max'=>255),
			array('unposted_docs', 'default', 'setOnEmpty' => true, 'value' => null),
			array('manager_info_id, name, second_name, surname, phone, email, unposted_docs', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'managerInfo' => array(self::BELONGS_TO, 'Manager', 'manager_info_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'manager_info_id' => null,
			'name' => Yii::t('app', 'Name'),
			'second_name' => Yii::t('app', 'Second Name'),
			'surname' => Yii::t('app', 'Surname'),
			'phone' => Yii::t('app', 'Phone'),
			'email' => Yii::t('app', 'Email'),
			'unposted_docs' => Yii::t('app', 'Unposted Docs'),
			'managerInfo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('manager_info_id', $this->manager_info_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('second_name', $this->second_name, true);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('unposted_docs', $this->unposted_docs, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}