<?php

/**
 * This is the model base class for the table "doc_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DocStatus".
 *
 * Columns in table "doc_status" available as properties of the model,
 * followed by relations of table "doc_status" available as properties of the model.
 *
 * @property integer $doc_status_id
 * @property string $doc_status_descr
 *
 * @property DocLinks[] $docLinks
 */
abstract class BaseDocStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'doc_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DocStatus|DocStatuses', $n);
	}

	public static function representingColumn() {
		return 'doc_status_descr';
	}

	public function rules() {
		return array(
			array('doc_status_descr', 'required'),
			array('doc_status_descr', 'length', 'max'=>45),
			array('doc_status_id, doc_status_descr', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'docLinks' => array(self::HAS_MANY, 'DocLinks', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'doc_status_id' => Yii::t('app', 'Doc Status'),
			'doc_status_descr' => Yii::t('app', 'Doc Status Descr'),
			'docLinks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('doc_status_id', $this->doc_status_id);
		$criteria->compare('doc_status_descr', $this->doc_status_descr, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}