<?php

/**
 * This is the model base class for the table "device_part".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DevicePart".
 *
 * Columns in table "device_part" available as properties of the model,
 * followed by relations of table "device_part" available as properties of the model.
 *
 * @property integer $device_part_id
 * @property integer $device_id
 * @property integer $part_id
 *
 * @property Device $device
 * @property DevicePartDescr $part
 */
abstract class BaseDevicePart extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'device_part';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DevicePart|DeviceParts', $n);
	}

	public static function representingColumn() {
		return 'device_part_id';
	}

	public function rules() {
		return array(
			array('device_id, part_id', 'required'),
			array('device_id, part_id', 'numerical', 'integerOnly'=>true),
			array('device_part_id, device_id, part_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'device' => array(self::BELONGS_TO, 'Device', 'device_id'),
			'part' => array(self::BELONGS_TO, 'DevicePartDescr', 'part_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'device_part_id' => Yii::t('app', 'Device Part'),
			'device_id' => null,
			'part_id' => null,
			'device' => null,
			'part' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('device_part_id', $this->device_part_id);
		$criteria->compare('device_id', $this->device_id);
		$criteria->compare('part_id', $this->part_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}